// 36 distinct customer-angle video scripts. Each maps a VISION customer problem →
// a 1000-Viral-Hooks template → a meme/number-driven short. emotion drives the
// first-3s feeling (accent color + music + opener reaction). Keep them DIFFERENT.
module.exports = [
  { id: "c01", emotion: "frustration", hook: "Are you still calling 6 shops to find ONE thing?",
    scenes: [{ big: "6", text: "shops called", emoji: "📞" }, { big: "0", text: "actually picked up", emoji: "🦗" }, { text: "I asked ONE bee. Got every answer.", emoji: "🐝" }], cta: "Stop dialing. Just ask." },
  { id: "c02", emotion: "shock", hook: "You have ONE weirdly specific question. The internet has 0 answers.",
    scenes: [{ text: "'Ship it by Friday, customized, under ₹500?'" }, { big: "0", text: "websites can answer that" }, { text: "The shop's bee replied in 2 seconds.", emoji: "⚡" }], cta: "Ask anything. Get a real answer." },
  { id: "c03", emotion: "frustration", hook: "Finding a place WITHOUT vs WITH the bee.",
    scenes: [{ big: "5", text: "apps: Google, Maps, site, Insta, a call", emoji: "😵‍💫" }, { big: "1", text: "chat with the bee", emoji: "🐝" }, { text: "Same answer. 1 minute vs 20." }], cta: "One chat. Done." },
  { id: "c04", emotion: "frustration", hook: "If you LOVE being left on read by businesses, skip this.",
    scenes: [{ text: "'Hi, are you open?'" }, { big: "3 days", text: "later... still 'Seen'", emoji: "💀" }, { text: "The bee replies in 2 seconds. 24/7.", emoji: "🐝" }], cta: "Never get ghosted again." },
  { id: "c05", emotion: "curiosity", hook: "The biggest cheat code for finding the ONE good shop near you.",
    scenes: [{ text: "Not the 50 average ones.", emoji: "👀" }, { text: "'Within 1km, who's actually known for this?'" }, { big: "5 sec", text: "ranked answer, with ratings." }], cta: "Find the best, not the nearest." },
  { id: "c06", emotion: "frustration", hook: "Every business website, in ONE sentence:",
    scenes: [{ big: "5", text: "tabs open", emoji: "🗂️" }, { big: "0", text: "answers to YOUR question" }, { text: "Just ask the bee instead." }], cta: "Skip the website maze." },
  { id: "c07", emotion: "curiosity", hook: "Can't find a wooden water bottle ANYWHERE?",
    scenes: [{ big: "10", text: "sites scrolled, nothing", emoji: "😩" }, { text: "'Who near me makes custom ones?'" }, { text: "The bee finds shops that actually do." }], cta: "Ask for the exact thing you want." },
  { id: "c08", emotion: "relief", hook: "POV: you want to ask about a bike for sale but hate calling strangers.",
    scenes: [{ emoji: "😬", text: "Call a stranger? No thanks." }, { text: "So you text their bee instead." }, { big: "100", text: "questions, zero awkwardness", emoji: "😮‍💨" }], cta: "Ask everything. Call no one." },
  { id: "c09", emotion: "shock", hook: "The shop you GAMBLED on vs the one the bee found.",
    scenes: [{ big: "2.1★", text: "random pick", emoji: "🙃" }, { big: "4.8★", text: "bee's pick in 5 seconds", emoji: "✨" }, { text: "Highest-rated, nearest, one ask." }], cta: "Stop gambling on shops." },
  { id: "c10", emotion: "shock", hook: "Google can't tell you this. The bee can.",
    scenes: [{ text: "'Any beds free RIGHT NOW?'", emoji: "🛏️" }, { big: "2", text: "beds. ₹4,500. Today." }, { text: "Live info Google never has." }], cta: "Answers that are true today." },
  { id: "c11", emotion: "relief", hook: "Tell me you've asked 5 shops the same 5 questions — without telling me.",
    scenes: [{ big: "25", text: "messages typed", emoji: "😮‍💨" }, { text: "Ask the bee ONCE." }, { text: "It remembers. It answers. Every shop." }], cta: "Ask once, not 25 times." },
  { id: "c12", emotion: "curiosity", hook: "It's 1AM. You need an answer. Everything's closed.",
    scenes: [{ emoji: "🌙", text: "Every shop: closed." }, { text: "Their bee: wide awake." }, { big: "24/7", text: "answers, even at 3AM" }], cta: "The bee never sleeps." },
  { id: "c13", emotion: "relief", hook: "Need something rare second-hand? Don't beg in 4 WhatsApp groups.",
    scenes: [{ big: "4", text: "groups, 0 replies", emoji: "📵" }, { text: "Ask the bee to find whoever HAS it." }, { text: "It checks every agent for you." }], cta: "Find anything. Ask anyone." },
  { id: "c14", emotion: "frustration", hook: "How many minutes have you wasted on hold this year?",
    scenes: [{ big: "100s", text: "of minutes. Gone.", emoji: "⏳" }, { text: "The bee answers instantly." }, { big: "0", text: "hold music. ever." }], cta: "Zero hold. Real answers." },
  { id: "c15", emotion: "shock", hook: "You called 7 shops just to compare ONE price.",
    scenes: [{ big: "7", text: "calls", emoji: "📞" }, { text: "The bee lists every price, side by side." }, { big: "1", text: "ask. all prices.", emoji: "💸" }], cta: "Compare in seconds." },
  { id: "c16", emotion: "curiosity", hook: "There's a shop 800m away that's PERFECT. You'll never find it.",
    scenes: [{ emoji: "📍", text: "Buried on page 6 of Google." }, { text: "The bee knows it by what it's good at." }, { text: "Ask. It surfaces." }], cta: "Discover what's hiding nearby." },
  { id: "c17", emotion: "frustration", hook: "The hours online said OPEN. You drove there. CLOSED.",
    scenes: [{ emoji: "🚗", text: "Wasted trip." }, { big: "0", text: "trust in Google hours" }, { text: "The bee's info is live, from the owner." }], cta: "Never drive to a closed door." },
  { id: "c18", emotion: "relief", hook: "Getting a quote shouldn't take 5 phone calls.",
    scenes: [{ big: "5", text: "calls for one quote", emoji: "😤" }, { text: "Ask the bee. It gets quotes for you." }, { text: "Overnight, while you sleep." }], cta: "Quotes without the calls." },
  { id: "c19", emotion: "shock", hook: "What if every shop answered you in YOUR language?",
    scenes: [{ text: "Tamil, English — however you ask.", emoji: "🗣️" }, { text: "The bee replies the same way." }, { text: "No more 'sorry, no English'." }], cta: "Ask in your language." },
  { id: "c20", emotion: "curiosity", hook: "Before you buy it, ask the people who already did.",
    scenes: [{ emoji: "🤔", text: "'Is it actually worth ₹2,000?'" }, { text: "Real experiences from real locals." }, { text: "On the bee, not buried in 100 reviews." }], cta: "Know before you go." },
  { id: "c21", emotion: "frustration", hook: "You DM'd the shop on Instagram. It's been 6 days.",
    scenes: [{ big: "6 days", text: "'Seen'", emoji: "💀" }, { text: "Their bee would've replied in 2 seconds." }, { text: "Day or night." }], cta: "Get replies, not 'Seen'." },
  { id: "c22", emotion: "relief", hook: "Planning anything in a new city is 20 open tabs.",
    scenes: [{ big: "20", text: "tabs", emoji: "😵" }, { text: "Ask the local bee: stays, food, prices." }, { big: "1", text: "chat instead", emoji: "🐝" }], cta: "Plan with one bee." },
  { id: "c23", emotion: "shock", hook: "Whoever replies FIRST usually wins your money.",
    scenes: [{ big: "78%", text: "go with the first reply", sub: "MIT / InsideSales" }, { text: "So the fastest shop wins — not the best." }, { text: "The bee makes everyone reply instantly." }], cta: "May the fastest answer win." },
  { id: "c24", emotion: "curiosity", hook: "The answer you want is NEVER on the website.",
    scenes: [{ text: "'Eggless? Gluten-free? Today?'", emoji: "🍰" }, { big: "0", text: "websites say" }, { text: "The bee asks the owner and tells you." }], cta: "Ask the question that matters." },
  { id: "c25", emotion: "frustration", hook: "Why does finding a plumber cost 10 calls AND a commission?",
    scenes: [{ big: "10", text: "calls", emoji: "📞" }, { text: "Apps add a fee just to connect you." }, { text: "The bee connects you direct. Free." }], cta: "No middleman. No fee." },
  { id: "c26", emotion: "relief", hook: "Imagine never repeating yourself to a business again.",
    scenes: [{ text: "It remembers what you asked.", emoji: "🧠" }, { text: "And what you like." }, { big: "0", text: "starting over" }], cta: "It remembers, so you don't." },
  { id: "c27", emotion: "shock", hook: "Half the good shops near you are basically INVISIBLE online.",
    scenes: [{ big: "65%", text: "have no findable phone", sub: "in your city" }, { text: "You can't reach them. They lose you." }, { text: "The bee makes them answerable." }], cta: "Reach the unreachable." },
  { id: "c28", emotion: "curiosity", hook: "What's the weirdest thing you'd ask a shop if you weren't shy?",
    scenes: [{ emoji: "👀", text: "'Open? Parking? Pet-friendly? Price?'" }, { text: "Ask the bee ALL of it." }, { big: "0", text: "judgment" }], cta: "Ask the awkward stuff." },
  { id: "c29", emotion: "frustration", hook: "3 shops. 3 prices. 3 phone calls. 1 headache.",
    scenes: [{ big: "3", text: "calls to compare", emoji: "🤯" }, { text: "The bee compares them for you." }, { text: "Cheapest, nearest, best — instantly." }], cta: "Compare without the calls." },
  { id: "c30", emotion: "relief", hook: "It's late, you need something, and you don't want to call.",
    scenes: [{ emoji: "🌙", text: "'Who's open near me right now?'" }, { text: "The bee checks live and tells you." }, { big: "24/7", text: "always answering" }], cta: "Ask any time." },
  { id: "c31", emotion: "shock", hook: "You'll waste 40 hours this year just trying to REACH businesses.",
    scenes: [{ big: "40 hrs", text: "calling, waiting, searching", emoji: "⏳" }, { text: "The bee gives it back." }, { big: "2 sec", text: "answers" }], cta: "Take your time back." },
  { id: "c32", emotion: "curiosity", hook: "The best info about your city isn't on Google. It's in people's heads.",
    scenes: [{ text: "Free slots. Real prices. What's good.", emoji: "🧠" }, { text: "Locals drop it. The bee serves it." }, { text: "Fresh, today, true." }], cta: "Tap into local know-how." },
  { id: "c33", emotion: "frustration", hook: "'We'll call you back.' (They never call back.)",
    scenes: [{ emoji: "📵", text: "The callback that never comes." }, { text: "The bee answers now — no callback." }, { big: "0", text: "waiting" }], cta: "Get the answer now." },
  { id: "c34", emotion: "relief", hook: "What if asking any local business felt like texting a friend?",
    scenes: [{ text: "Same app. Same chat.", emoji: "💬" }, { text: "Every shop, one place." }, { big: "1", text: "app for all of it" }], cta: "Local, made simple." },
  { id: "c35", emotion: "shock", hook: "Every unanswered question is a sale lost — and your time lost.",
    scenes: [{ big: "1000s", text: "of questions unanswered daily", emoji: "❓" }, { text: "The bee answers them — for free." }, { text: "Everybody wins." }], cta: "Ask. Get answered." },
  { id: "c36", emotion: "curiosity", hook: "POV: you found it before anyone else because you asked the bee.",
    scenes: [{ emoji: "😎", text: "Free slot. Best price. First." }, { text: "While they're still calling around." }, { big: "1", text: "chat ahead of everyone" }], cta: "Be the one who already knows." },
];
